<?php
/**
  * Function partial which creates custom fields created by ACF PRO.
  *
  * @package culu
  *
  *
  */

if( function_exists('acf_add_local_field_group') ):

 acf_add_local_field_group(array(
 	'key' => 'group_5cbdf95e3f992',
 	'title' => 'Staff Profile',
 	'fields' => array(
 		array(
 			'key' => 'field_5cbdfc7db1044',
 			'label' => 'Photo',
 			'name' => 'photo',
 			'type' => 'image',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'return_format' => 'array',
 			'preview_size' => 'thumbnail',
 			'library' => 'all',
 			'min_width' => '',
 			'min_height' => '',
 			'min_size' => '',
 			'max_width' => '',
 			'max_height' => '',
 			'max_size' => '',
 			'mime_types' => '',
 		),
 		array(
 			'key' => 'field_5cbdf967b103f',
 			'label' => 'First Name',
 			'name' => 'first_name',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 1,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => 'First Name',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 		array(
 			'key' => 'field_5cbdfc43b1040',
 			'label' => 'Last Name',
 			'name' => 'last_name',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 1,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => 'Last name',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 		array(
 			'key' => 'field_5cf003a7086c2',
 			'label' => 'Degree',
 			'name' => 'degree',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 		array(
 			'key' => 'field_5cbdfc55b1041',
 			'label' => 'Title',
 			'name' => 'title',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 1,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 		array(
 			'key' => 'field_5cbdfc60b1042',
 			'label' => 'Email',
 			'name' => 'email',
 			'type' => 'email',
 			'instructions' => '',
 			'required' => 1,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'prepend' => '',
 			'append' => '',
 		),
 		array(
 			'key' => 'field_5cbdfc69b1043',
 			'label' => 'Phone',
 			'name' => 'phone',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 1,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 		array(
 			'key' => 'field_5cbdfd5bcddd4',
 			'label' => 'Consultation',
 			'name' => 'consultation',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 		array(
 			'key' => 'field_5d3b181a0ffe7',
 			'label' => 'Office Location',
 			'name' => 'office_location',
 			'type' => 'text',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'prepend' => '',
 			'append' => '',
 			'maxlength' => '',
 		),
 		array(
 			'key' => 'field_5d3b182c0ffe8',
 			'label' => 'Areas of Expertise',
 			'name' => 'areas_of_expertise',
 			'type' => 'textarea',
 			'instructions' => 'Add expertise separated by a comma.',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'maxlength' => '',
 			'rows' => '',
 			'new_lines' => '',
 		),
 		array(
 			'key' => 'field_5d3b184f0ffe9',
 			'label' => 'ORCID ID',
 			'name' => 'orcid_id',
 			'type' => 'url',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 		),
 		array(
 			'key' => 'field_5d3b185a0ffea',
 			'label' => 'Linkedin Profile',
 			'name' => 'linkedin_profile',
 			'type' => 'url',
 			'instructions' => '',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 		),
 		array(
 			'key' => 'field_5d3b18d90ffeb',
 			'label' => 'Liaison Areas',
 			'name' => 'liaison_areas',
 			'type' => 'textarea',
 			'instructions' => 'Add liaison areas separated by a comma.',
 			'required' => 0,
 			'conditional_logic' => 0,
 			'wrapper' => array(
 				'width' => '',
 				'class' => '',
 				'id' => '',
 			),
 			'default_value' => '',
 			'placeholder' => '',
 			'maxlength' => '',
 			'rows' => '',
 			'new_lines' => '',
 		),
 	),
 	'location' => array(
 		array(
 			array(
 				'param' => 'post_type',
 				'operator' => '==',
 				'value' => 'staff',
 			),
 		),
 	),
 	'menu_order' => 0,
 	'position' => 'normal',
 	'style' => 'default',
 	'label_placement' => 'top',
 	'instruction_placement' => 'label',
 	'hide_on_screen' => array(
 		0 => 'excerpt',
 		1 => 'discussion',
 		2 => 'comments',
 		3 => 'format',
 		4 => 'page_attributes',
 		5 => 'featured_image',
 		6 => 'categories',
 		7 => 'tags',
 		8 => 'send-trackbacks',
 	),
 	'active' => true,
 	'description' => '',
 ));

 endif;
