<?php
$seedprod_basic_lpage = '
{
    "no_conflict_mode": false,
    "no_index": false,
    "seo_title": "",
    "seo_description": "",
    "favicon": "",
    "social_thumbnail": "",
    "enable_recaptcha": false,
    "template_id":"",
    "post_title":"",
    "post_name":"",
    "post_status":"",
    "show_powered_by_link":false,
    "facebook_app_id":"",
    "affiliate_url":"",
    "header_scripts":"",
    "body_scripts":"",
    "footer_scripts":"",
    "conversion_scripts":"",
    "disable_default_excluded_urls": false,
    "include_exclude_type": "0",
    "include_list": "",
    "exclude_list": "",
    "bypass_phrase": "",
    "bypass_expires": "2",
    "bypass_cookie": false,
    "access_by_ip":"",
    "access_by_role":[],
    "redirect_login_page":false,
    "redirect_mode":false,
    "redirect_url":"",
    "domain_mapping_status":false,
    "domain_mapping":"",
    "domain_mapping_force_https":false,
    "exclude_list_404":"",
    "email_integration_id":"",
    "document":{
        "sections":[],
        "settings":{
           "bgStyle": "s",
           "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
           "bgColor":"#FFFFFF",
           "bgImage":"",
           "bgDimming":0,
           "bgOverlayColor":"",
           "bgPosition":"cover",
           "buttonColor":"#000000",
           "headerColor":"#000000",
           "linkColor":"#FF0000",
           "linkDarkerColor":"#cc0000",
           "textColor":"#272727",
           "textFont":"\'Helvetica Neue\', Arial, sans-serif",
           "textFontVariant":"400",
           "headerFont":"\'Helvetica Neue\', Arial, sans-serif",
           "headerFontVariant":"400",
           "contentPosition":"1",
           "customCss":"",
           "headCss":"",
           "mobileCss":"",
           "placeholderCss":"",
           "useVideoBg":false,
           "useVideoBgUrl":"",
           "useSlideshowBg": false,
           "useSlideshowImgs": [""]

        }
     }
 }
 ';

 $seedprod_lite_block_templates = '
 {
  "document":{
      "bgStyle": "s",
      "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
      "bgColor":"#FFFFFF",
      "bgImage":"",
      "bgDimming":0,
      "bgOverlayColor":"",
      "bgPosition":"cover",
      "buttonColor":"#000000",
      "headerColor":"#000000",
      "linkColor":"#FF0000",
      "linkDarkerColor":"#cc0000",
      "textColor":"#272727",
      "textFont":"\'Helvetica Neue\', Arial, sans-serif",
      "textFontVariant":"400",
      "headerFont":"\'Helvetica Neue\', Arial, sans-serif",
      "headerFontVariant":"400",
      "contentPosition":"1",
      "customCss":"",
      "headCss":"",
      "mobileCss":"",
      "placeholderCss":"",
      "useVideoBg":false,
      "useVideoBgUrl":"",
      "useSlideshowBg": false,
      "useSlideshowImgs": [""]
   },
   "row":{
      "bgStyle": "s",
      "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
      "colGutter": 0,
      "width":"1000",
      "bgColor":"",
      "bgImage":"",
      "bgPosition":"",
      "marginTop": "",
      "shadow":"",
      "paddingTop": "0",
      "paddingBottom": "0",
      "paddingLeft": "0",
      "paddingRight": "0",
      "paddingSync": true,
      "borderRadiusTL": "",
      "borderRadiusTR": "",
      "borderRadiusBL": "",
      "borderRadiusBR": "",
      "borderRadiusSync":true,
      "borderTop": "0",
      "borderBottom": "0",
      "borderLeft": "0",
      "borderRight": "0",
      "borderSync": true,
      "borderStyle":"solid"
   },
   "section":{
      "bgStyle": "s",
      "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
      "contentWidth":1,
      "width":"1000",
      "bgColor":"",
      "bgImage":"",
      "bgPosition":"",
      "marginTop": "",
      "shadow":"",
      "paddingTop": "10",
      "paddingBottom": "10",
      "paddingLeft": "10",
      "paddingRight": "10",
      "paddingSync": true,
      "borderRadiusTL": "",
      "borderRadiusTR": "",
      "borderRadiusBL": "",
      "borderRadiusBR": "",
      "borderRadiusSync":true,
      "borderTop": "0",
      "borderBottom": "0",
      "borderLeft": "0",
      "borderRight": "0",
      "borderSync": true,
      "borderStyle":"solid"
   },
   "col":{
    "bgStyle": "s",
    "bgGradient":{ "type": "linear","position": "center", "angle": 0,"color1":"","color1location":0,"color2":"","color2location":100 },
    "colWidth":"",
    "bgColor":"",
    "bgImage":"",
    "bgPosition":"",
    "marginTop": "",
    "shadow":"",
    "paddingTop": "",
    "paddingBottom": "",
    "paddingLeft": "",
    "paddingRight": "",
    "paddingSync": true,
    "borderRadiusTL": "",
    "borderRadiusTR": "",
    "borderRadiusBL": "",
    "borderRadiusBR": "",
    "borderRadiusSync":true,
    "borderTop": "0",
    "borderBottom": "0",
    "borderLeft": "0",
    "borderRight": "0",
    "borderSync": true,
    "borderStyle":"solid"
 },
   "icon":{
     "icon":"fas fa-angle-double-down",
     "color":"",
     "fontSize":"48",
     "align":"center",
     "textShadow":"",
     "marginTop": "0",
     "paddingTop": "",
     "paddingBottom": "",
     "paddingLeft": "",
     "paddingRight": "",
     "paddingSync": true
   },
   "starrating":{
    "label":"",
    "scale":"5",
    "rating":"5",
    "iconSize":"24",
    "spaceBetween":"",
    "align":"center",
    "color":"#fdd835",
    "textColor":"",
    "font": "",
    "fontVariant": "",
    "fontSize": "",
    "fontSize_mobile": "",
    "lineHeight": "",
    "lineHeight_mobile": "",
    "letterSpacing": "",
    "letterSpacing_mobile": "",
    "typographyBold": "",
    "typographyItalic": "",
    "typographyUnderline": "",
    "typographyLetterCase": "",
    "textShadow":"",
    "marginTop": "0",
    "paddingTop": "",
    "paddingBottom": "",
    "paddingLeft": "",
    "paddingRight": "",
    "paddingSync": true
  },
  "testimonial":{
    "items": [{ "img": "", "txt": "\"This is the greatest thing since sliced bread!\"","name": "John Smith", "title": "CEO" }],
    "align": "left",
    "navColor":"d",
    "commentBubble":true,
    "autoPlay":true,
    "speed":5,
    "marginTop": "0",
    "paddingTop": "10",
    "paddingBottom": "10",
    "paddingLeft": "10",
    "paddingRight": "10",
    "paddingSync": true,
    "textColor": "#444444",
    "font": "",
    "fontVariant": "",
    "fontSize": "",
    "fontSize_mobile": "",
    "lineHeight": "",
    "lineHeight_mobile": "",
    "letterSpacing": "",
    "letterSpacing_mobile": "",
    "typographyBold": "",
    "typographyItalic": true,
    "typographyUnderline": "",
    "typographyLetterCase": "",
    "nameColor": "",
    "namefont": "",
    "namefontVariant": "",
    "namefontSize": "",
    "namefontSize_mobile": "",
    "namelineHeight": "",
    "namelineHeight_mobile": "",
    "nameletterSpacing": "",
    "nameletterSpacing_mobile": "",
    "nametypographyBold": "",
    "nametypographyItalic": "",
    "nametypographyUnderline": "",
    "nametypographyLetterCase": ""
   },
   "feature":{
    "tag": "h2",
    "icon":"",
    "iconColor":"",
    "iconFontSize":"38",
    "headerTxt": "' . __( 'My Feature or Benefit', 'coming-soon' ) . '",
    "layout": "image",
    "txt": "Description",
    "width": "",
    "height": "",
    "align": "left",
    "altTxt": "",
    "src": "",
    "unit":"px",
    "marginTop": "0",
    "paddingTop": "",
    "paddingBottom": "",
    "paddingLeft": "",
    "paddingRight": "",
    "paddingSync": true,
    "font": "",
    "fontVariant": "",
    "fontSize": "",
    "fontSize_mobile": "",
    "lineHeight": "",
    "lineHeight_mobile": "",
    "letterSpacing": "",
    "letterSpacing_mobile": "",
    "typographyBold": "",
    "typographyItalic": "",
    "typographyUnderline": "",
    "typographyLetterCase": "",
    "headerfont": "",
    "headerfontVariant": "",
    "headerfontSize": "",
    "headerfontSize_mobile": "",
    "headerlineHeight": "",
    "headerlineHeight_mobile": "",
    "headerletterSpacing": "",
    "headerletterSpacing_mobile": "",
    "headertypographyBold": "",
    "headertypographyItalic": "",
    "headertypographyUnderline": "",
    "headertypographyLetterCase": ""
   },
   "iconfeature":{
    "tag": "h2",
    "icon":"fas fa-check",
    "iconColor":"",
    "iconFontSize":"38",
    "headerTxt": "' . __( 'My Feature or Benefit', 'coming-soon' ) . '",
    "layout": "icon",
    "txt": "Description",
    "width": "200",
    "height": "",
    "align": "left",
    "altTxt": "",
    "src": "",
    "unit":"px",
    "marginTop": "0",
    "paddingTop": "",
    "paddingBottom": "",
    "paddingLeft": "",
    "paddingRight": "",
    "paddingSync": true,
    "font": "",
    "fontVariant": "",
    "fontSize": "",
    "fontSize_mobile": "",
    "lineHeight": "",
    "lineHeight_mobile": "",
    "letterSpacing": "",
    "letterSpacing_mobile": "",
    "typographyBold": "",
    "typographyItalic": "",
    "typographyUnderline": "",
    "typographyLetterCase": "",
    "headerfont": "",
    "headerfontVariant": "",
    "headerfontSize": "",
    "headerfontSize_mobile": "",
    "headerlineHeight": "",
    "headerlineHeight_mobile": "",
    "headerletterSpacing": "",
    "headerletterSpacing_mobile": "",
    "headertypographyBold": "",
    "headertypographyItalic": "",
    "headertypographyUnderline": "",
    "headertypographyLetterCase": ""
   },
   "header":{
      "headerTxt": "' . __( 'My Awesome Headline', 'coming-soon' ) . '",
      "tag": "h1",
      "textColor": "",
      "bgColor": "",
      "beforeIcon": "",
      "afterIcon": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": ""
    },
    "button":{
      "action": "link",
      "link": "",
      "openNewWindow": false,
      "noFollow": false,
      "btnTxt": "Call To Action",
      "btnStyle": "",
      "btnSubTxt": "",
      "btnSubTextSize": "",
      "textColor": "#ffffff",
      "bgColor": "",
      "btnPaddingTop": "16",
      "btnPaddingLeft": "20",
      "btnSize":"4",
      "beforeIcon": "",
      "afterIcon": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "4",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "22",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": ""
    },
    "text":{
      "txt": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam commodo velit ex, non ultrices leo auctor at. Integer blandit ex velit, vel aliquam sem tempor eu. Pellentesque sem tortor, elementum et nisi sed, convallis pharetra lorem. Aenean rhoncus rhoncus ex, in dictum massa dictum et. Morbi at nisl fermentum, condimentum tortor a, laoreet leo. Curabitur laoreet diam a metus tincidunt, sed dapibus orci venenatis.",
      "textColor": "",
      "bgColor": "",
      "beforeIcon": "",
      "afterIcon": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "left",
      "typographyLetterCase": ""
    },
    "facebooklike":{
      "buttonType":"like",
      "layoutType":"standard",
      "buttonSize":"small",
      "shareButton":false,
      "targetUrl":"currentpage",
      "targetUrlFormat":"plainpermalink",     
      "customlinkurl":"",
      "align": "left",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "facebookcomments":{
      "orderBy" :"social",
      "lazyLoad" :false,
      "colorScheme" : "dark",
      "numComments" : "5",
      "targetUrl":"currentpage",
      "targetUrlFormat":"plainpermalink",     
      "customlinkurl":"",
      "align": "center",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "facebookpage":{
      "layoutPage":"timeline",
      "multiLayoutPage":["timeline"],
      "smallHeader" : true,
      "coverPhoto" : true,
      "profilePhoto" : true,
      "hideCTA" : true,
      "height" : "500",   
      "customlinkurl":"https://www.facebook.com/seedprodwp/",
      "align": "center",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "facebookembed":{
      "embedType":"post",
      "fullPost" : true,
      "fullScreen" : true,
      "autoPlay" : true,
      "captions" : true,
      "parentComment" : true,
      "height" : "500",   
      "postlinkurl":"https://www.facebook.com/seedprodwp/posts/1788470497975496",
      "videolinkurl":"https://business.facebook.com/seedprodwp/videos/226940179165922/",
      "commentlinkurl":"https://www.facebook.com/zuck/posts/10102577175875681?comment_id=1193531464007751&reply_comment_id=654912701278942",
      "align": "center",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "contactform":{
      "formId":"",
      "textColor":"",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "align": "center",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "left",
      "typographyLetterCase": ""
    },
    "giveaway":{
      "giveawayId":"",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "align": "center"
    },
    "image":{
      "link": "",
      "openNewWindow": false,
      "noFollow": false,
      "unit":"px",
      "src": "",
      "altTxt": "",
      "link": "",
      "width": "",
      "height": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "imagePadding": "",
      "align": "center",
      "shadow": "",
      "imageBorderRadius": "",
      "imageBorderTop": "0",
      "imageBorderBottom": "0",
      "imageBorderLeft": "0",
      "imageBorderRight": "0",
      "imageBorderSync": true,
      "imageBorderStyle":"solid",
      "imageBorderColor": "",
      "blockTemplateId":false
    },
    "divider":{
      "style": "solid",
      "width": "90",
      "height": "1",
      "color": "",
      "align": "center",
      "marginTop": "0",
      "paddingTop": "10",
      "paddingBottom": "10",
      "paddingLeft": "0",
      "paddingRight": "0",
      "paddingSync": false,
      "shadow": ""
    },
    "spacer": {
      "height": 60
    },
    "accordion":{
      "spaceBetween":"24",
      "items": [{"txt": "Accordion 1", "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam commodo velit ex, non ultrices leo auctor at."},{"txt": "Accordion 2", "details": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam commodo velit ex, non ultrices leo auctor at."}],
      "bgColor": "",
      "dividerColor": "",
      "textColor": "",
      "iconColor": "",
      "openIconColor": "",
      "closedIcon": "fas fa-plus",
      "openIcon": "fas fa-minus",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "left",
      "typographyLetterCase": "",
      "headerColor":"",
      "headerOpenColor":"",
      "headerfont": "",
      "headerfontVariant": "",
      "headerfontSize": "",
      "headerfontSize_mobile": "",
      "headerlineHeight": "",
      "headerlineHeight_mobile": "",
      "headerletterSpacing": "",
      "headerletterSpacing_mobile": "",
      "headertypographyBold": "",
      "headertypographyItalic": "",
      "headertypographyUnderline": "",
      "headertypographyLetterCase": ""
    },
    "anchor": {
      "name": ""
    },
    "customhtml":{
      "code": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "shortcode":{
      "shortcode": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "login":{
      "align": "left",
      "redirectUrl": "",
      "marginTop": "",
      "paddingTop": "10",
      "paddingBottom": "10",
      "paddingLeft": "10",
      "paddingRight": "10",
      "paddingSync": true,
      "rowSpacing": "10",
      "linkColor": "",
      "linkHoverColor": "",
      "loggedInText": "Logged in as {user}",
      "labelRememberme": "Remember Me",
      "labelLostpass": "Lost your password?",
      "labelTextUser": "Username or Email Address",
      "labelTextUserPlaceholder": "",
      "labelTextPass": "Password",
      "labelTextPassPlaceholder": "",
      "labelSpacing": "5",
      "labelTextColor": "",
      "labelTextFont": "",
      "labelTextSize": "",
      "labelTextFontVariant": "",
      "fieldTextColor": "#444444",
      "fieldSize": "md",
      "fieldWidth": "100",
      "fieldTextFontSize": "",
      "fieldPaddingVertical": "6",
      "fieldPaddingHorizontal": "10",
      "fieldTextFont": "",
      "fieldTextFontVariant": "",
      "fieldBGColor": "#FFFFFF",
      "fieldBorderColor": "#dddddd",
      "fieldborderTop": "1",
      "fieldborderBottom": "1",
      "fieldborderLeft": "1",
      "fieldborderRight": "1",
      "fieldBorderRadius": "3",
      "btnText": "Log In",
      "btnTextFontSize": "15",
      "btnTextFont": "",
      "btnTextFontVariant": "",
      "btnTextColor": "#FFFFFF",
      "btnSize": "1",
      "btnBgColor": "",
      "btnPaddingVertical": "8",
      "btnPaddingHorizontal": "12",
      "btnBorderRadius": "3"
    },
    "video":{
      "type":"youtube",
      "code": "",
      "youtubeUrl": "https://www.youtube.com/watch?v=MUXoqm3VpRo",
      "width": "100",
      "align": "center",
      "shadow":"",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true
    },
    "countdown":{
      "countdownType":"",
      "vtHours":"0",
      "vtMinutes":"30",
      "vtSeconds":"0",
      "action":1,
      "thankyouTxt": "",
      "redirectUrl": "",
      "size":"md",
      "timezone": "' . seedprod_lite_get_default_timezone() . '",
      "endDate": "",
      "endTime": "",
      "endTimestamp": "",
      "bgColor": "",
      "labelColor": "",
      "dayTxt":"Days",
      "hourTxt":"Hours",
      "minuteTxt":"Minutes",
      "secondTxt":"Seconds",
      "spaceBetween":"20",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": "uppercase",
      "blockTemplateId":false
    },
    "bulletlist":{
      "layout": "v",
      "spaceBetween":"10",
      "items": [{ "icon": "fas fa-check", "txt": "Item 1" }],
      "textColor": "",
      "iconColor": "",
      "beforeIcon": "",
      "afterIcon": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "left",
      "typographyLetterCase": "",
      "blockTemplateId":false
    },
    "nav":{
      "layout": "h",
      "spaceBetween":"20",
      "items": [{ "url": "", "txt": "About","openNewWindow":"","noFollow":"" },{ "url": "", "txt": "Contact","openNewWindow":"","noFollow":"" }],
      "textColor": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "left",
      "typographyLetterCase": ""
    },
    "form":{
      "items": []
    },
    "optinform":{
      "align": "center",
      "items": [
        { "type": "email", "label":"' . __( 'Enter Your Email', 'coming-soon' ) . '","txt":"' . __( 'Email', 'coming-soon' ) . '","width":"100","required": true,"display": true},
        { "type": "name", "label":"' . __( 'Enter Your Name', 'coming-soon' ) . '","txt":"' . __( 'Name', 'coming-soon' ) . '","width":"100","required": false, "display": true},
        { "type": "optin_confirm", "label":"' . __( 'Optin Confirmation', 'coming-soon' ) . '","txt":"' . __( 'Optin Confirmation', 'coming-soon' ) . '","width":"100","required": true,"display": false}
      ],
      "action":"1",
      "redirectUrl":"",
      "thankyouTxt":"Thank You, we\'ll be in touch soon.",
      "btnSize":"3",
      "inputSize":"",
      "bgColor":"",
      "btnWidth":"100",
      "btnTxt":"Submit",
      "btnSubTxt":"",
      "btnPaddingTop": "16",
      "btnPaddingLeft": "20",
      "inputPadding": "8",
      "fieldBGColor": "#ffffff",
      "fieldTextColor": "#444444",
      "fieldBorderColor": "#dddddd",
      "fieldborderTop": "1",
      "fieldborderBottom": "1",
      "fieldborderLeft": "1",
      "fieldborderRight": "1",
      "fieldborderSync": true,
      "beforeIcon":"",
      "afterIcon":"",
      "shadow": "",
      "borderRadius": "3",
      "font": "",
      "fontVariant": "",
      "fontSize": "18",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "gap": false,
      "blockTemplateId":false
    },
    "progressbar":{
      "txt": "My Text",
      "textShadow": "",
      "shadow": "",
      "width": "60",
      "color": "",
      "outerColor": "#F7F7F7",
      "borderRadius": "3",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "blockTemplateId":false
    },
    "socialprofiles":{
      "iconStyle":"1",
      "iconPadding": 15,
      "iconSize": 24,
      "iconColor": "",
      "size": "md",
      "items": [{ "type": "facebook", "label":"","url":"" },{ "type": "twitter", "label":"","url":"" },{ "type": "instagram", "label":"","url":"" },{ "type": "youtube", "label":"","url":"" }],
      "spaceBetween": "10",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "align": "center",
      "blockTemplateId":false
    },
    "socialsharing":{
      "size": "sm",
      "items": [{ "type": "facebook", "label":"", "meta":"","url":"" },{ "type": "twitter", "label":"", "meta":"","url":"" }],
      "spaceBetween": "20",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "align": "center"
    },
    "wcaddtocart":{
      "productId": "",
      "directToCheckout": false,
      "btnTxt": "Add To Cart",
      "btnStyle": "",
      "btnSubTxt": "",
      "btnSubTextSize": "",
      "textColor": "#ffffff",
      "bgColor": "",
      "btnPaddingTop": "16",
      "btnPaddingLeft": "20",
      "btnSize":"4",
      "beforeIcon": "",
      "afterIcon": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "borderRadius": "4",
      "border": "",
      "borderStyle": "",
      "borderSize": "",
      "borderColor": "",
      "shadow": "",
      "textShadow": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "22",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "align": "center",
      "typographyLetterCase": ""
    },
    "wccart":{
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "headerColor": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "typographyLetterCase": "",
      "align": "",
      "btnStyle": "flat",
      "btnBgColor": "",
      "btnBorderRadius": "",
      "btnShadow": "",
      "btnLineHeight": "",
      "fieldBGColor": "",
      "fieldTextColor": "",
      "fieldBorderColor": "",
      "fieldborderTop": "1",
      "fieldborderRight": "1",
      "fieldborderBottom": "1",
      "fieldborderLeft": "1",
      "fieldborderSync": "true",
      "alertInfoHlColor": "",
      "alertErrorHlColor": "",
      "alertSuccessHlColor": "",
      "cartFieldBorderColor": "",
      "cartborderTop": "1",
      "cartborderRight": "1",
      "cartborderBottom": "1",
      "cartborderLeft": "1",
      "cartborderSync": "true",
      "cartBorderRadius": "",
      "cartBgColor": "",
      "cartTextColor": "",
      "cartFont": "",
      "cartFontVariant": "",
      "cartHeaderBgColor": "",
      "cartHeaderFont": "",
      "cartHeaderFontVariant": "",
      "cartHeaderColor": ""
    },
  "wccheckout":{
      "css": "",
      "layoutColumns": "2",
      "headerColor": "",
      "font": "",
      "fontVariant": "",
      "fontSize": "",
      "fontSize_mobile": "",
      "lineHeight": "",
      "lineHeight_mobile": "",
      "letterSpacing": "",
      "letterSpacing_mobile": "",
      "typographyBold": "",
      "typographyItalic": "",
      "typographyUnderline": "",
      "typographyLetterCase": "",
      "align": "",
      "fieldBGColor": "",
      "fieldTextColor": "",
      "fieldBorderColor": "",
      "fieldborderTop": "1",
      "fieldborderRight": "1",
      "fieldborderBottom": "1",
      "fieldborderLeft": "1",
      "fieldborderSync": "true",
      "borderRadius": "",
      "labelColor": "",
      "labelfont": "",
      "labelfontVariant": "",
      "labelfontSize": "",
      "labelfontSize_mobile": "",
      "labellineHeight": "",
      "labellineHeight_mobile": "",
      "labelletterSpacing": "",
      "labelletterSpacing_mobile": "",
      "labeltypographyBold": "",
      "labeltypographyItalic": "",
      "labeltypographyUnderline": "",
      "labeltypographyLetterCase": "",
      "labelalign": "",
      "rowSpacing": "6",
      "btnStyle": "flat",
      "btnBgColor": "",
      "btnBorderRadius": "",
      "btnShadow": "",
      "btnLineHeight": "",
      "alertInfoHlColor": "",
      "alertErrorHlColor": "",
      "alertSuccessHlColor": "",
      "cartFieldBorderColor": "",
      "cartborderTop": "1",
      "cartborderRight": "1",
      "cartborderBottom": "1",
      "cartborderLeft": "1",
      "cartborderSync": "true",
      "cartBorderRadius": "",
      "cartBgColor": "",
      "cartTextColor": "",
      "cartFont": "",
      "cartFontVariant": "",
      "cartHeaderBgColor": "",
      "cartHeaderFont": "",
      "cartHeaderFontVariant": "",
      "cartHeaderColor": "",
      "paymentBgColor": "",
      "paymentTextColor": "#333",
      "paymentFont": "",
      "paymentFontVariant": ""
    },

 "wccustomproductsgrid":{
      "columns": "4",
      "pagination": false,
      "limit": "-1",
      "showItemsCount": false,
      "showOrderBy": false,
      "selectProductIds": false,
      "productIds": [],
      "selectProductSkus": false,
      "productSkus": [],
      "selectCategories": false,
      "productCategories": [],
      "queryCategoriesOperator": "IN",
      "selectTags": false,
      "productTags": [],
      "queryTagsOperator": "IN",
      "selectGroup": false,
      "productGroups": "",
      "selectByVisibility": false,
      "productVisibility": "",
      "queryByAttribute": false,
      "queryAttribute": "",
      "queryAttributeTerms": [],
      "queryTermsOperator": "IN",
      "querySource": "all_products",
      "queryInclude": "",
      "queryIncludeBy": "",
      "queryIncludeTerm": "",
      "queryExclude": "",
      "queryExcludeBy": "",
      "queryExcludeTerm": "",
      "queryOrderBy": [],
      "queryOrder": "ASC",
      "align": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "btnStyle": "flat",
      "btnBgColor": "",
      "btnBorderRadius": "",
      "descriptionfont": "",
      "descriptionfontVariant": "",
      "descriptionfontSize": "",
      "descriptionfontSize_mobile": "",
      "descriptionlineHeight": "",
      "descriptionlineHeight_mobile": "",
      "descriptionletterSpacing": "",
      "descriptionletterSpacing_mobile": "",
      "descriptiontypographyBold": "",
      "descriptiontypographyItalic": "",
      "descriptiontypographyUnderline": "",
      "descriptionalign": "",
      "descriptiontypographyLetterCase": "",
      "pricefont": "",
      "pricefontVariant": "",
      "pricefontSize": "",
      "pricefontSize_mobile": "",
      "pricelineHeight": "",
      "pricelineHeight_mobile": "",
      "priceletterSpacing": "",
      "priceletterSpacing_mobile": "",
      "pricetypographyBold": "",
      "pricetypographyItalic": "",
      "pricetypographyUnderline": "",
      "pricealign": "",
      "pricetypographyLetterCase": "",
      "priceColor": "",
      "saleColor":"",
      "buttonStyle": "flat",
      "buttonBgColor": "",
      "buttonShadow": "",
      "buttonLineHeight": "",
      "buttonfont": "",
      "buttonfontVariant": "",
      "buttonfontSize": "",
      "buttonfontSize_mobile": "",
      "buttonlineHeight": "",
      "buttonlineHeight_mobile": "",
      "buttonletterSpacing": "",
      "buttonletterSpacing_mobile": "",
      "buttontypographyBold": "",
      "buttontypographyItalic": "",
      "buttontypographyUnderline": "",
      "buttonalign": "",
      "buttontypographyLetterCase": "",
      "buttonSize":"4",
      "buttonPaddingTop": "16",
      "buttonPaddingLeft": "20",
      "buttonBorderRadius": "",
      "imageShadow": "",
      "imageBorderRadius": "3",
      "imageBorderStyle": "solid",
      "imageBorderColor": "#ccc",
      "imageBorderTop": "1",
      "imageBorderBottom": "1",
      "imageBorderLeft": "1",
      "imageBorderRight": "1",
      "imageBorderSync": true,
      "imagePadding": ""
    },
    "wcfeaturedproductsgrid":{
      "columns": "4",
      "pagination": false,
      "limit": "-1",
      "showItemsCount": false,
      "showOrderBy": false,
      "selectProductIds": false,
      "productIds": [],
      "selectProductSkus": false,
      "productSkus": [],
      "selectCategories": false,
      "productCategories": [],
      "queryCategoriesOperator": "IN",
      "selectTags": false,
      "productTags": [],
      "queryTagsOperator": "IN",
      "selectGroup": false,
      "productGroups": "",
      "selectByVisibility": false,
      "productVisibility": "",
      "queryByAttribute": false,
      "queryAttribute": "",
      "queryAttributeTerms": [],
      "queryTermsOperator": "IN",
      "querySource": "featured_products",
      "queryInclude": "",
      "queryIncludeBy": "",
      "queryIncludeTerm": "",
      "queryExclude": "",
      "queryExcludeBy": "",
      "queryExcludeTerm": "",
      "queryOrderBy": [],
      "queryOrder": "ASC",
      "align": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "btnStyle": "flat",
      "btnBgColor": "",
      "btnBorderRadius": "",
      "descriptionfont": "",
      "descriptionfontVariant": "",
      "descriptionfontSize": "",
      "descriptionfontSize_mobile": "",
      "descriptionlineHeight": "",
      "descriptionlineHeight_mobile": "",
      "descriptionletterSpacing": "",
      "descriptionletterSpacing_mobile": "",
      "descriptiontypographyBold": "",
      "descriptiontypographyItalic": "",
      "descriptiontypographyUnderline": "",
      "descriptionalign": "",
      "descriptiontypographyLetterCase": "",
      "pricefont": "",
      "pricefontVariant": "",
      "pricefontSize": "",
      "pricefontSize_mobile": "",
      "pricelineHeight": "",
      "pricelineHeight_mobile": "",
      "priceletterSpacing": "",
      "priceletterSpacing_mobile": "",
      "pricetypographyBold": "",
      "pricetypographyItalic": "",
      "pricetypographyUnderline": "",
      "pricealign": "",
      "pricetypographyLetterCase": "",
      "priceColor": "",
      "buttonStyle": "flat",
      "buttonBgColor": "",
      "buttonShadow": "",
      "buttonLineHeight": "",
      "buttonfont": "",
      "buttonfontVariant": "",
      "buttonfontSize": "",
      "buttonfontSize_mobile": "",
      "buttonlineHeight": "",
      "buttonlineHeight_mobile": "",
      "buttonletterSpacing": "",
      "buttonletterSpacing_mobile": "",
      "buttontypographyBold": "",
      "buttontypographyItalic": "",
      "buttontypographyUnderline": "",
      "buttonalign": "",
      "buttontypographyLetterCase": "",
      "buttonSize":"4",
      "buttonPaddingTop": "16",
      "buttonPaddingLeft": "20",
      "buttonBorderRadius": "",
      "imageShadow": "",
      "imageBorderRadius": "",
      "imageBorderStyle": "",
      "imageBorderColor": "",
      "imageBorderTop": "1",
      "imageBorderBottom": "1",
      "imageBorderLeft": "1",
      "imageBorderRight": "1",
      "imageBorderSync": true,
      "imagePadding": ""
    },
    "wcsaleproductsgrid":{
      "columns": "4",
      "pagination": false,
      "limit": "-1",
      "showItemsCount": false,
      "showOrderBy": false,
      "selectProductIds": false,
      "productIds": [],
      "selectProductSkus": false,
      "productSkus": [],
      "selectCategories": false,
      "productCategories": [],
      "queryCategoriesOperator": "IN",
      "selectTags": false,
      "productTags": [],
      "queryTagsOperator": "IN",
      "selectGroup": false,
      "productGroups": "",
      "selectByVisibility": false,
      "productVisibility": "",
      "queryByAttribute": false,
      "queryAttribute": "",
      "queryAttributeTerms": [],
      "queryTermsOperator": "IN",
      "querySource": "sale_products",
      "queryInclude": "",
      "queryIncludeBy": "",
      "queryIncludeTerm": "",
      "queryExclude": "",
      "queryExcludeBy": "",
      "queryExcludeTerm": "",
      "queryOrderBy": [],
      "queryOrder": "ASC",
      "align": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "btnStyle": "flat",
      "btnBgColor": "",
      "btnBorderRadius": "",
      "descriptionfont": "",
      "descriptionfontVariant": "",
      "descriptionfontSize": "",
      "descriptionfontSize_mobile": "",
      "descriptionlineHeight": "",
      "descriptionlineHeight_mobile": "",
      "descriptionletterSpacing": "",
      "descriptionletterSpacing_mobile": "",
      "descriptiontypographyBold": "",
      "descriptiontypographyItalic": "",
      "descriptiontypographyUnderline": "",
      "descriptionalign": "",
      "descriptiontypographyLetterCase": "",
      "pricefont": "",
      "pricefontVariant": "",
      "pricefontSize": "",
      "pricefontSize_mobile": "",
      "pricelineHeight": "",
      "pricelineHeight_mobile": "",
      "priceletterSpacing": "",
      "priceletterSpacing_mobile": "",
      "pricetypographyBold": "",
      "pricetypographyItalic": "",
      "pricetypographyUnderline": "",
      "pricealign": "",
      "pricetypographyLetterCase": "",
      "priceColor": "",
      "buttonStyle": "flat",
      "buttonBgColor": "",
      "buttonShadow": "",
      "buttonLineHeight": "",
      "buttonfont": "",
      "buttonfontVariant": "",
      "buttonfontSize": "",
      "buttonfontSize_mobile": "",
      "buttonlineHeight": "",
      "buttonlineHeight_mobile": "",
      "buttonletterSpacing": "",
      "buttonletterSpacing_mobile": "",
      "buttontypographyBold": "",
      "buttontypographyItalic": "",
      "buttontypographyUnderline": "",
      "buttonalign": "",
      "buttontypographyLetterCase": "",
      "buttonSize":"4",
      "buttonPaddingTop": "16",
      "buttonPaddingLeft": "20",
      "buttonBorderRadius": "",
      "imageShadow": "",
      "imageBorderRadius": "",
      "imageBorderStyle": "",
      "imageBorderColor": "",
      "imageBorderTop": "1",
      "imageBorderBottom": "1",
      "imageBorderLeft": "1",
      "imageBorderRight": "1",
      "imageBorderSync": true,
      "imagePadding": ""
    },
    "wcbestsellingproductsgrid":{
      "columns": "4",
      "pagination": false,
      "limit": "-1",
      "showItemsCount": false,
      "showOrderBy": false,
      "selectProductIds": false,
      "productIds": [],
      "selectProductSkus": false,
      "productSkus": [],
      "selectCategories": false,
      "productCategories": [],
      "queryCategoriesOperator": "IN",
      "selectTags": false,
      "productTags": [],
      "queryTagsOperator": "IN",
      "selectGroup": false,
      "productGroups": "",
      "selectByVisibility": false,
      "productVisibility": "",
      "queryByAttribute": false,
      "queryAttribute": "",
      "queryAttributeTerms": [],
      "queryTermsOperator": "IN",
      "querySource": "best_selling_products",
      "queryInclude": "",
      "queryIncludeBy": "",
      "queryIncludeTerm": "",
      "queryExclude": "",
      "queryExcludeBy": "",
      "queryExcludeTerm": "",
      "queryOrderBy": [],
      "queryOrder": "ASC",
      "align": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "btnStyle": "flat",
      "btnBgColor": "",
      "btnBorderRadius": "",
      "descriptionfont": "",
      "descriptionfontVariant": "",
      "descriptionfontSize": "",
      "descriptionfontSize_mobile": "",
      "descriptionlineHeight": "",
      "descriptionlineHeight_mobile": "",
      "descriptionletterSpacing": "",
      "descriptionletterSpacing_mobile": "",
      "descriptiontypographyBold": "",
      "descriptiontypographyItalic": "",
      "descriptiontypographyUnderline": "",
      "descriptionalign": "",
      "descriptiontypographyLetterCase": "",
      "pricefont": "",
      "pricefontVariant": "",
      "pricefontSize": "",
      "pricefontSize_mobile": "",
      "pricelineHeight": "",
      "pricelineHeight_mobile": "",
      "priceletterSpacing": "",
      "priceletterSpacing_mobile": "",
      "pricetypographyBold": "",
      "pricetypographyItalic": "",
      "pricetypographyUnderline": "",
      "pricealign": "",
      "pricetypographyLetterCase": "",
      "priceColor": "",
      "buttonStyle": "flat",
      "buttonBgColor": "",
      "buttonShadow": "",
      "buttonLineHeight": "",
      "buttonfont": "",
      "buttonfontVariant": "",
      "buttonfontSize": "",
      "buttonfontSize_mobile": "",
      "buttonlineHeight": "",
      "buttonlineHeight_mobile": "",
      "buttonletterSpacing": "",
      "buttonletterSpacing_mobile": "",
      "buttontypographyBold": "",
      "buttontypographyItalic": "",
      "buttontypographyUnderline": "",
      "buttonalign": "",
      "buttontypographyLetterCase": "",
      "buttonSize":"4",
      "buttonPaddingTop": "16",
      "buttonPaddingLeft": "20",
      "buttonBorderRadius": "",
      "imageShadow": "",
      "imageBorderRadius": "",
      "imageBorderStyle": "",
      "imageBorderColor": "",
      "imageBorderTop": "1",
      "imageBorderBottom": "1",
      "imageBorderLeft": "1",
      "imageBorderRight": "1",
      "imageBorderSync": true,
      "imagePadding": ""
    },
    "wcrecentproductsgrid":{
      "columns": "4",
      "pagination": false,
      "limit": "-1",
      "showItemsCount": false,
      "showOrderBy": false,
      "selectProductIds": false,
      "productIds": [],
      "selectProductSkus": false,
      "productSkus": [],
      "selectCategories": false,
      "productCategories": [],
      "queryCategoriesOperator": "IN",
      "selectTags": false,
      "productTags": [],
      "queryTagsOperator": "IN",
      "selectGroup": false,
      "productGroups": "",
      "selectByVisibility": false,
      "productVisibility": "",
      "queryByAttribute": false,
      "queryAttribute": "",
      "queryAttributeTerms": [],
      "queryTermsOperator": "IN",
      "querySource": "recent_products",
      "queryInclude": "",
      "queryIncludeBy": "",
      "queryIncludeTerm": "",
      "queryExclude": "",
      "queryExcludeBy": "",
      "queryExcludeTerm": "",
      "queryOrderBy": [],
      "queryOrder": "ASC",
      "align": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "btnStyle": "flat",
      "btnBgColor": "",
      "btnBorderRadius": "",
      "descriptionfont": "",
      "descriptionfontVariant": "",
      "descriptionfontSize": "",
      "descriptionfontSize_mobile": "",
      "descriptionlineHeight": "",
      "descriptionlineHeight_mobile": "",
      "descriptionletterSpacing": "",
      "descriptionletterSpacing_mobile": "",
      "descriptiontypographyBold": "",
      "descriptiontypographyItalic": "",
      "descriptiontypographyUnderline": "",
      "descriptionalign": "",
      "descriptiontypographyLetterCase": "",
      "pricefont": "",
      "pricefontVariant": "",
      "pricefontSize": "",
      "pricefontSize_mobile": "",
      "pricelineHeight": "",
      "pricelineHeight_mobile": "",
      "priceletterSpacing": "",
      "priceletterSpacing_mobile": "",
      "pricetypographyBold": "",
      "pricetypographyItalic": "",
      "pricetypographyUnderline": "",
      "pricealign": "",
      "pricetypographyLetterCase": "",
      "priceColor": "",
      "buttonStyle": "flat",
      "buttonBgColor": "",
      "buttonShadow": "",
      "buttonLineHeight": "",
      "buttonfont": "",
      "buttonfontVariant": "",
      "buttonfontSize": "",
      "buttonfontSize_mobile": "",
      "buttonlineHeight": "",
      "buttonlineHeight_mobile": "",
      "buttonletterSpacing": "",
      "buttonletterSpacing_mobile": "",
      "buttontypographyBold": "",
      "buttontypographyItalic": "",
      "buttontypographyUnderline": "",
      "buttonalign": "",
      "buttontypographyLetterCase": "",
      "buttonSize":"4",
      "buttonPaddingTop": "16",
      "buttonPaddingLeft": "20",
      "buttonBorderRadius": "",
      "imageShadow": "",
      "imageBorderRadius": "",
      "imageBorderStyle": "",
      "imageBorderColor": "",
      "imageBorderTop": "1",
      "imageBorderBottom": "1",
      "imageBorderLeft": "1",
      "imageBorderRight": "1",
      "imageBorderSync": true,
      "imagePadding": ""
    },
    "wctopratedproductsgrid":{
      "columns": "4",
      "pagination": false,
      "limit": "-1",
      "showItemsCount": false,
      "showOrderBy": false,
      "selectProductIds": false,
      "productIds": [],
      "selectProductSkus": false,
      "productSkus": [],
      "selectCategories": false,
      "productCategories": [],
      "queryCategoriesOperator": "IN",
      "selectTags": false,
      "productTags": [],
      "queryTagsOperator": "IN",
      "selectGroup": false,
      "productGroups": "",
      "selectByVisibility": false,
      "productVisibility": "",
      "queryByAttribute": false,
      "queryAttribute": "",
      "queryAttributeTerms": [],
      "queryTermsOperator": "IN",
      "querySource": "top_rated_products",
      "queryInclude": "",
      "queryIncludeBy": "",
      "queryIncludeTerm": "",
      "queryExclude": "",
      "queryExcludeBy": "",
      "queryExcludeTerm": "",
      "queryOrderBy": [],
      "queryOrder": "ASC",
      "align": "",
      "marginTop": "0",
      "paddingTop": "",
      "paddingBottom": "",
      "paddingLeft": "",
      "paddingRight": "",
      "paddingSync": true,
      "btnStyle": "flat",
      "btnBgColor": "",
      "btnBorderRadius": "",
      "descriptionfont": "",
      "descriptionfontVariant": "",
      "descriptionfontSize": "",
      "descriptionfontSize_mobile": "",
      "descriptionlineHeight": "",
      "descriptionlineHeight_mobile": "",
      "descriptionletterSpacing": "",
      "descriptionletterSpacing_mobile": "",
      "descriptiontypographyBold": "",
      "descriptiontypographyItalic": "",
      "descriptiontypographyUnderline": "",
      "descriptionalign": "",
      "descriptiontypographyLetterCase": "",
      "pricefont": "",
      "pricefontVariant": "",
      "pricefontSize": "",
      "pricefontSize_mobile": "",
      "pricelineHeight": "",
      "pricelineHeight_mobile": "",
      "priceletterSpacing": "",
      "priceletterSpacing_mobile": "",
      "pricetypographyBold": "",
      "pricetypographyItalic": "",
      "pricetypographyUnderline": "",
      "pricealign": "",
      "pricetypographyLetterCase": "",
      "priceColor": "",
      "buttonStyle": "flat",
      "buttonBgColor": "",
      "buttonShadow": "",
      "buttonLineHeight": "",
      "buttonfont": "",
      "buttonfontVariant": "",
      "buttonfontSize": "",
      "buttonfontSize_mobile": "",
      "buttonlineHeight": "",
      "buttonlineHeight_mobile": "",
      "buttonletterSpacing": "",
      "buttonletterSpacing_mobile": "",
      "buttontypographyBold": "",
      "buttontypographyItalic": "",
      "buttontypographyUnderline": "",
      "buttonalign": "",
      "buttontypographyLetterCase": "",
      "buttonSize":"4",
      "buttonPaddingTop": "16",
      "buttonPaddingLeft": "20",
      "buttonBorderRadius": "",
      "imageShadow": "",
      "imageBorderRadius": "",
      "imageBorderStyle": "",
      "imageBorderColor": "",
      "imageBorderTop": "1",
      "imageBorderBottom": "1",
      "imageBorderLeft": "1",
      "imageBorderRight": "1",
      "imageBorderSync": true,
      "imagePadding": ""
    }

 }
 ';
